DROP TABLE BUYER;
DROP TABLE PURCHASE;
DROP TABLE SHIPMENT;

CREATE TABLE BUYER (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR(80) NOT NULL,
    LASTNAME VARCHAR(80) NOT NULL
);

CREATE TABLE PURCHASE(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    BUYER_ID BIGSERIAL,
    SHIPMENT_ID BIGSERIAL,
    DATA DATE,
    CONSTRAINT BUYER_FOREIGN_KEY FOREIGN KEY (BUYER_ID) REFERENCES BUYER (ID),
    CONSTRAINT SHIPMENT_FOREIGN_KEY FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (ID)
);

CREATE TABLE SHIPMENT(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    TITLE VARCHAR(80) NOT NULL,
    COST DECIMAL(10, 2) NOT NULL
);


